name: elixir-current
version: 'dev'
architectures: [amd64]
summary: Current version of Elixir.
description: |
  Version of Elixir language build from the tip of master in official
  repository https://github.com/elixir-lang/elixir

  Expects last Erlang version from https://erlang-solutions.com to be installed
  on host system.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  elixir:
    command: usr/local/bin/elixir
    plugs: [home]

  elixirc:
    command: usr/local/bin/elixirc
    plugs: [home]

  iex:
    command: usr/local/bin/iex
    plugs: [home]

  mix:
    command: usr/local/bin/mix
    plugs: [home]

parts:
  elixir:
    plugin: make
    source: https://github.com/elixir-lang/elixir.git
    source-depth: 1
    source-branch: master
    after: [erlangrepo]
    organize:
      usr/local/lib/elixir/bin/mix: tmp/removed1
      usr/local/bin/mix: tmp/removed2
    stage:
      - -tmp/
      - usr/local
    prime:
      - usr/local/bin
      - usr/local/share
      - usr/local/lib/elixir/lib
      - usr/local/lib/elixir/bin/elixir
      - usr/local/lib/elixir/bin/elixirc
      - usr/local/lib/elixir/bin/iex

  erlangrepo:
    plugin: nil
    # snapcraft offers no way to update sources/PPAs before build-packages are installed
    # so installing necessary build-packages manually
    prepare: |
      apt install -y wget
      wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      dpkg -i erlang-solutions_1.0_all.deb
      apt update
      apt install -y erlang-dev erlang-base erlang-parsetools erlang-inets


  resources:
    after: [elixir]
    plugin: dump
    source: resources
    organize:
      bin/mix: usr/local/bin/mix
      bin/dummy-mix: usr/local/lib/elixir/bin/mix
      #bin/snap-erl: usr/lib/erlang/bin/erl
    prime:
      - usr/local/bin/mix
      - usr/local/lib/elixir/bin/mix
      #- usr/lib/erlang/bin/erl
